name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # manual start

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # mandatory for push

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync ${{ github.repository }} -b main
